### ISSUE TITLE
struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by t0mtee** [leamsii/DK-Tropical-Freeze-Model-Extractor#2]
Hi, I'm trying to upscale the DKTF UI elements and need to get into the TXTR files. This is the only tool I've found that can do that. Running convert.py gives this error:
```
Traceback (most recent call last):
  File "convert.py", line 157, in <module>
    TXTR_DATA = getTXTRData(file_path) #Returns the raw image data and the header information
  File "C:\Users\tomt0\Desktop\DK-Tropical-Freeze-Model-Extractor-1.0\txtr_extractor\txtr_mapper.py", line 347, in getTXTRData
    META.setProperties([
  File "C:\Users\tomt0\Desktop\DK-Tropical-Freeze-Model-Extractor-1.0\txtr_extractor\txtr_mapper.py", line 197, in setProperties
    self.updatePropertyValues()
  File "C:\Users\tomt0\Desktop\DK-Tropical-Freeze-Model-Extractor-1.0\txtr_extractor\txtr_mapper.py", line 203, in updatePropertyValues
    p.value = struct.unpack(formats[p.byte_size], self.data[p.offset : p.offset + p.byte_size])[0]
struct.error: unpack requires a buffer of 4 bytes
```
How can I fix this?

**Comment by leamsii** [comment]
Looks like the file you're using is not supported by the tool. Mind uploading it here?

**Comment by t0mtee** [comment]
[all my files](https://we.tl/t-q3wddBEEyU)

I did realise, however, that I doubt I'll be able to repack these files so this idea may not be possible at this time

**Comment by leamsii** [comment]
These texture files are missing the META header, they might be incompatible, sorry.
